# Kitty configuration for KDE Plasma session
include /home/aesc/.config/kitty/common.conf

# Independent KDE theme (Breeze Dark / custom)
include theme.conf

# BEGIN_KITTY_THEME
# GitHub Dark Colorblind
include current-theme.conf
# END_KITTY_THEME