color0 #0e2843
color1 #fd4663
color2 #74ace7
color3 #7b79e2
color4 #af79e2
color5 #92beec
color6 #9796e9
color7 #f2f2f3
color8 #616971
color9 #fd4663
color10 #74ace7
color11 #7b79e2
color12 #af79e2
color13 #92beec
color14 #9796e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #0b1e32
background            #0b1e32
foreground            #f2f2f3
selection_foreground  #afb2b6
selection_background  #0e2843
active_border_color   #74ace7
inactive_border_color #0e2843
url_color             #74ace7

active_tab_foreground   #181e25
active_tab_background   #74ace7
inactive_tab_foreground #afb2b6
inactive_tab_background #0e2843
cursor_trail_color      #afb2b6
