color0 #334b47
color1 #ffb4ab
color2 #a3d578
color3 #aed18d
color4 #82d5c7
color5 #a3d578
color6 #aed18d
color7 #d7e6e1
color8 #7c9690
color9 #ffb4ab
color10 #a3d578
color11 #aed18d
color12 #82d5c7
color13 #a3d578
color14 #aed18d
color15 #d7e6e1

cursor                #d7e6e1
cursor_text_color     #091613
background            #091613
foreground            #d7e6e1
selection_foreground  #b1ccc6
selection_background  #334b47
active_border_color   #a3d578
inactive_border_color #334b47
url_color             #a3d578

active_tab_foreground   #1a3700
active_tab_background   #a3d578
inactive_tab_foreground #b1ccc6
inactive_tab_background #334b47
cursor_trail_color      #b1ccc6
