# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x000000ff
rootcolor = 0x0f141cff
bordercolor = 0x8791a5ff
dropcolor = 0x50d8ec80
splitcolor = 0xa7c8ffff
focuscolor = 0x50d8ecff
maximizescreencolor = 0x82d3e1ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xa7c8ffff
globalcolor = 0x004f58ff
overlaycolor = 0x004f58ff
jump_label_decorate_fg_color = 0xdee2efff
jump_label_decorate_bg_color = 0x252a33ff
jump_label_decorate_focus_fg_color = 0x00363dff
jump_label_decorate_focus_bg_color = 0x50d8ecff
jump_label_decorate_border_color = 0x8791a5ff
group_bar_decorate_fg_color = 0xdee2efff
group_bar_decorate_bg_color = 0x252a33ff
group_bar_decorate_focus_fg_color = 0x00363dff
group_bar_decorate_focus_bg_color = 0x50d8ecff
group_bar_decorate_border_color = 0x8791a5ff
