# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x0d1b30ff
rootcolor = 0x0d1b30ff
bordercolor = 0x606770ff
dropcolor = 0x679ae480
splitcolor = 0xcc8566ff
focuscolor = 0x679ae4ff
maximizescreencolor = 0x685cd6ff
urgentcolor = 0xfd4663ff
scratchpadcolor = 0xcc8566ff
globalcolor = 0x0c408dff
overlaycolor = 0x19106fff
jump_label_decorate_fg_color = 0xf2f2f3ff
jump_label_decorate_bg_color = 0x132948ff
jump_label_decorate_focus_fg_color = 0x181d25ff
jump_label_decorate_focus_bg_color = 0x679ae4ff
jump_label_decorate_border_color = 0x606770ff
group_bar_decorate_fg_color = 0xf2f2f3ff
group_bar_decorate_bg_color = 0x132948ff
group_bar_decorate_focus_fg_color = 0x181d25ff
group_bar_decorate_focus_bg_color = 0x679ae4ff
group_bar_decorate_border_color = 0x606770ff
