# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x142e0fff
rootcolor = 0x142e0fff
bordercolor = 0x677565ff
dropcolor = 0x7ce46780
splitcolor = 0x56dcc6ff
focuscolor = 0x7ce467ff
maximizescreencolor = 0x56dc83ff
urgentcolor = 0xfd4663ff
scratchpadcolor = 0x56dcc6ff
globalcolor = 0x278514ff
overlaycolor = 0x136d31ff
jump_label_decorate_fg_color = 0xf2f3f2ff
jump_label_decorate_bg_color = 0x1f4517ff
jump_label_decorate_focus_fg_color = 0x1a2518ff
jump_label_decorate_focus_bg_color = 0x7ce467ff
jump_label_decorate_border_color = 0x677565ff
group_bar_decorate_fg_color = 0xf2f3f2ff
group_bar_decorate_bg_color = 0x1f4517ff
group_bar_decorate_focus_fg_color = 0x1a2518ff
group_bar_decorate_focus_bg_color = 0x7ce467ff
group_bar_decorate_border_color = 0x677565ff
