color0 #3d4758
color1 #ffb4ab
color2 #50d8ec
color3 #82d3e1
color4 #a7c8ff
color5 #50d8ec
color6 #82d3e1
color7 #dee2ef
color8 #8791a5
color9 #ffb4ab
color10 #50d8ec
color11 #82d3e1
color12 #a7c8ff
color13 #50d8ec
color14 #82d3e1
color15 #dee2ef

cursor                #dee2ef
cursor_text_color     #0f141c
background            #0f141c
foreground            #dee2ef
selection_foreground  #bdc7dc
selection_background  #3d4758
active_border_color   #50d8ec
inactive_border_color #3d4758
url_color             #50d8ec

active_tab_foreground   #00363d
active_tab_background   #50d8ec
inactive_tab_foreground #bdc7dc
inactive_tab_background #3d4758
cursor_trail_color      #bdc7dc
