color0 #15313c
color1 #fd4663
color2 #67d4e4
color3 #5c89d6
color4 #867ae3
color5 #93e0ec
color6 #96b4e9
color7 #f2f3f3
color8 #606e70
color9 #fd4663
color10 #67d4e4
color11 #5c89d6
color12 #867ae3
color13 #93e0ec
color14 #96b4e9
color15 #f2f3f3

cursor                #f2f3f3
cursor_text_color     #10242d
background            #10242d
foreground            #f2f3f3
selection_foreground  #afb5b6
selection_background  #15313c
active_border_color   #67d4e4
inactive_border_color #15313c
url_color             #67d4e4

active_tab_foreground   #182325
active_tab_background   #67d4e4
inactive_tab_foreground #afb5b6
inactive_tab_background #15313c
cursor_trail_color      #afb5b6
