color0 #112440
color1 #fd4663
color2 #679ae4
color3 #7b72ee
color4 #cc8566
color5 #93b7ec
color6 #9e96e9
color7 #f2f2f3
color8 #606770
color9 #fd4663
color10 #679ae4
color11 #7b72ee
color12 #cc8566
color13 #93b7ec
color14 #9e96e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #0d1b30
background            #0d1b30
foreground            #f2f2f3
selection_foreground  #afb2b6
selection_background  #112440
active_border_color   #679ae4
inactive_border_color #112440
url_color             #679ae4

active_tab_foreground   #181d25
active_tab_background   #679ae4
inactive_tab_foreground #afb2b6
inactive_tab_background #112440
cursor_trail_color      #afb2b6
