color0 #1b3d14
color1 #ff4b66
color2 #7ce467
color3 #56dc83
color4 #56dcc6
color5 #a2ec93
color6 #95e9b1
color7 #f2f3f2
color8 #677565
color9 #ff4b66
color10 #7ce467
color11 #56dc83
color12 #56dcc6
color13 #a2ec93
color14 #95e9b1
color15 #f2f3f2

cursor                #f2f3f2
cursor_text_color     #142e0f
background            #142e0f
foreground            #f2f3f2
selection_foreground  #b0b6af
selection_background  #1b3d14
active_border_color   #7ce467
inactive_border_color #1b3d14
url_color             #7ce467

active_tab_foreground   #1a2518
active_tab_background   #7ce467
inactive_tab_foreground #b0b6af
inactive_tab_background #1b3d14
cursor_trail_color      #b0b6af
