color0 #182539
color1 #fd4663
color2 #6796e4
color3 #7e72ee
color4 #a768cf
color5 #93b4ec
color6 #a096e9
color7 #f2f2f3
color8 #616770
color9 #fd4663
color10 #6796e4
color11 #7e72ee
color12 #a768cf
color13 #93b4ec
color14 #a096e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #121c2b
background            #121c2b
foreground            #f2f2f3
selection_foreground  #afb2b6
selection_background  #182539
active_border_color   #6796e4
inactive_border_color #182539
url_color             #6796e4

active_tab_foreground   #181d25
active_tab_background   #6796e4
inactive_tab_foreground #afb2b6
inactive_tab_background #182539
cursor_trail_color      #afb2b6
