font_family JetBrainsMono Nerd Font
font_size 11.5
background_opacity 0.94
confirm_os_window_close 0
enable_audio_bell no
scrollback_lines 10000
window_padding_width 8
include themes/noctalia.conf

# Tonelico terminal appearance
include tonelico-comic-mono.conf


# BEGIN_KITTY_THEME
# Neowave
include current-theme.conf
# END_KITTY_THEME