# Shared Kitty base configuration
include /home/aesc/.config/kitty/common.conf
include /home/aesc/.config/kitty/themes/default.conf


# BEGIN_KITTY_THEME
# GitHub Dark Colorblind
include current-theme.conf
# END_KITTY_THEME