[theme.templates]
enable_builtin_templates = false
enable_community_templates = false
builtin_ids = []
community_ids = []

[theme.templates.user.kitty]
input_path = "/run/current-system/sw/share/noctalia/assets/templates/kitty/kitty.conf"
output_path = "/home/aesc/.config/kitty/profiles/mango/theme.conf"
post_hook = "pkill -SIGUSR1 -u $(id -u) -x kitty || true"

[theme.templates.user.gtk3]
input_path = "/run/current-system/sw/share/noctalia/assets/templates/gtk/gtk3.css"
output_path = [
  "/home/aesc/.local/state/theme-profiles/mango/generated/gtk3/noctalia.css",
  "/home/aesc/.config/gtk-3.0/theme-active.css"
]

[theme.templates.user.gtk4]
input_path = "/run/current-system/sw/share/noctalia/assets/templates/gtk/gtk4.css"
output_path = [
  "/home/aesc/.local/state/theme-profiles/mango/generated/gtk4/noctalia.css",
  "/home/aesc/.config/gtk-4.0/theme-active.css"
]

[theme.templates.user.qt]
input_path = "/run/current-system/sw/share/noctalia/assets/templates/qt/qtct.conf"
output_path = [
  "/home/aesc/.local/state/theme-profiles/mango/generated/qt/noctalia.conf",
  "/home/aesc/.config/qt5ct/colors/noctalia.conf",
  "/home/aesc/.config/qt6ct/colors/noctalia.conf"
]

[theme.templates.user.mango]
input_path = "/run/current-system/sw/share/noctalia/assets/templates/mango/mango.conf"
output_path = [
  "/home/aesc/.local/state/theme-profiles/mango/generated/mango/colors.conf",
  "/home/aesc/.config/mango/noctalia.conf"
]
post_hook = "mmsg dispatch reload_config"

[theme.templates.user.btop]
input_path = "/run/current-system/sw/share/noctalia/assets/templates/btop/btop.theme"
output_path = "/home/aesc/.local/state/theme-profiles/mango/generated/btop/noctalia.theme"

[theme.templates.user.cava]
input_path = "/run/current-system/sw/share/noctalia/assets/templates/cava/cava.ini"
output_path = "/home/aesc/.local/state/theme-profiles/mango/generated/cava/noctalia"

[theme.templates.user.obs]
input_path = "/home/aesc/.local/state/noctalia/community-templates/obs/matugen.obt"
output_path = [
  "/home/aesc/.local/state/theme-profiles/mango/generated/obs/matugen.obt",
  "/home/aesc/.config/obs-studio/themes/matugen.obt"
]

[theme.templates.user.prismlauncher]
input_path = "/home/aesc/.local/state/noctalia/community-templates/prismlauncher/prismlauncher.json"
output_path = [
  "/home/aesc/.local/state/theme-profiles/mango/generated/prismlauncher/theme.json",
  "/home/aesc/.local/share/PrismLauncher/themes/Matugen/theme.json"
]

[theme.templates.user.obsidian]
input_path = "/home/aesc/.local/state/noctalia/community-templates/obsidian/obsidian.css"
output_path = [
  "/home/aesc/.local/state/theme-profiles/mango/generated/obsidian/noctalia.css",
  "/home/aesc/Documents/Obsidian Vault/.obsidian/snippets/noctalia.css"
]
