# Kitty configuration for sway session
include /home/aesc/.config/kitty/common.conf

# Dynamic wallpaper theme from Noctalia
include /home/aesc/.config/kitty/themes/noctalia.conf

# BEGIN_KITTY_THEME
include current-theme.conf
# END_KITTY_THEME
